/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "rgb(var(--primary))",
        "primary-inverse": "rgb(var(--primary-inverse))",
        "primary-hover": "rgb(var(--primary-hover))",
        "primary-active-color": "rgb(var(--primary-active-color))",

        "primary-highlight":
          "rgb(var(--primary)/var(--primary-highlight-opacity))",
        "primary-highlight-inverse": "rgb(var(--primary-highlight-inverse))",
        "primary-highlight-hover":
          "rgb(var(--primary)/var(--primary-highlight-hover-opacity))",

        "primary-50": "rgb(var(--primary-50))",
        "primary-100": "rgb(var(--primary-100))",
        "primary-200": "rgb(var(--primary-200))",
        "primary-300": "rgb(var(--primary-300))",
        "primary-400": "rgb(var(--primary-400))",
        "primary-500": "rgb(var(--primary-500))",
        "primary-600": "rgb(var(--primary-600))",
        "primary-700": "rgb(var(--primary-700))",
        "primary-800": "rgb(var(--primary-800))",
        "primary-900": "rgb(var(--primary-900))",
        "primary-950": "rgb(var(--primary-950))",

        "surface-0": "rgb(var(--surface-0))",
        "surface-50": "rgb(var(--surface-50))",
        "surface-100": "rgb(var(--surface-100))",
        "surface-200": "rgb(var(--surface-200))",
        "surface-300": "rgb(var(--surface-300))",
        "surface-400": "rgb(var(--surface-400))",
        "surface-500": "rgb(var(--surface-500))",
        "surface-600": "rgb(var(--surface-600))",
        "surface-700": "rgb(var(--surface-700))",
        "surface-800": "rgb(var(--surface-800))",
        "surface-900": "rgb(var(--surface-900))",
        "surface-950": "rgb(var(--surface-950))",

        // Colors base
        base: "rgba(var(--base), <alpha-value>)",
        "base-alpha-4": "var(--base-alpha-4)",
        "base-alpha-12": "var(--base-alpha-12)",
        "base-alpha-20": "var(--base-alpha-20)",
        "base-alpha-30": "var(--base-alpha-30)",
        "base-alpha-58": "var(--base-alpha-58)",
        "base-light-20": "var(--base-light-20)",
        "base-dark-20": "var(--base-dark-20)",
        red: "var(--red)",
        "red-alpha-8": "var(--red-alpha-8)",
        green: "var(--green)",
        "green-alpha-8": "var(--green-alpha-8)",
        black: "var(--black)",
        "black-10": "var(--black-10)",
        "black-40": "var(--black-40)",
        "black-60": "var(--black-60)",
        "black-alpha-0": "var(--black-alpha-0)",
        "black-alpha-1": "var(--black-alpha-1)",
        "black-alpha-3": "var(--black-alpha-3)",
        "black-alpha-6": "var(--black-alpha-6)",
        "black-alpha-10": "var(--black-alpha-10)",
        "black-alpha-12": "var(--black-alpha-12)",
        "black-alpha-20": "var(--black-alpha-20)",
        "black-94": "var(--black-94)",
        "black-96": "var(--black-96)",
        "black-98": "var(--black-98)",
        white: "var(--white)",
        "white-alpha-6": "var(--white-alpha-6)",
        "white-alpha-20": "var(--white-alpha-20)",
        "white-alpha-88": "var(--white-alpha-88)",
        "white-dark-alpha-78": "var(--white-dark-alpha-78)",
        "ch-green": "var(--ch-green)",
        "ch-green-light": "var(--ch-green-light)",
        "ch-green-dark": "var(--ch-green-dark)",
        "ch-red": "var(--ch-red)",
        "ch-red-dark": "var(--ch-red-dark)",
        "red-dark": "var(--red-dark)",
        "orange-dark": "var(--orange-dark)",
        "yellow-dark": "var(--yellow-dark)",
        "green-dark": "var(--green-dark)",
        "indigo-dark": "var(--indigo-dark)",
        "purple-dark": "var(--purple-dark)",
        "red-light": "var(--red-light)",
        "orange-light": "var(--orange-light)",
        "yellow-light": "var(--yellow-light)",
        "green-light": "var(--green-light)",
        "indigo-light": "var(--indigo-light)",
        "purple-light": "var(--purple-light)",
        brown: "var(--brown)",
        clay: "var(--clay)",
        lime: "var(--lime)",
        cyan: "var(--cyan)",
        blue: "var(--blue)",
        pink: "var(--pink)",
        "brown-light": "var(--brown-light)",
        "clay-light": "var(--clay-light)",
        "lime-light": "var(--lime-light)",
        "cyan-light": "var(--cyan-light)",
        "blue-light": "var(--blue-light)",
        "pink-light": "var(--pink-light)",
        primary: "rgba(var(--base), <alpha-value>)", // Usage for primary with alpha
        "primary-inverse": "rgba(var(--base), <alpha-value>)", // same as primary
        "primary-hover": "var(--base-dark-20)",
        "primary-active-color": "var(--primary-active-color)",
      },

      fontFamily: {
        "tt-firs-text-normal": ["TT Firs Text Normal"],
      },
      boxShadow: {
        sm: "0px 1px 2px 0px #24242408",
        medium: "0px 2px 24px 0px #24242433",
        default: "0px 25px 30px 0px #00000033",
      },
    },
  },
  plugins: [],
};
